### ISSUE TITLE
wrong pid

### ISSUE THREAD

**Issue by arhi** [UP3D-gcode/UP3D#2]
mine up!plus2 don't show as 4745/2777 as you expect

device instance path is: USB\VID_4745&PID_277D\91387
matching device id: usb\vid_4745&pid_277d

so pid is 277D not 2777 

![capture](https://cloud.githubusercontent.com/assets/410177/18811930/5a63cb76-82c2-11e6-9205-bf250db1abda.JPG)

**Comment by kscheff** [comment]
Your UP PID can be added, when we get it to work - otherwise it won't make sense to add the PID without positive feedback.

Do you know if all Plus version have this PID? Any success on other UP! Plus users?

**Comment by yanivg101** [comment]
This is my UP2 Plus PID if it's help:
![up2 plus pid](https://cloud.githubusercontent.com/assets/6355171/18865153/84ed4854-84a2-11e6-801a-d21bff0d7f8b.jpg)

**Comment by arhi** [comment]
hm ... same ROM, your one is 0001 pid ..

**Comment by yanivg101** [comment]
I add here the output of up3dinfo:

> UP 3D PRINTER INFO:
> TypeID:277b Serial:84688 ROM:6.0900 Model:UP Plus 2(H) U1:1.00 U3:1 U4:102 U7:100
> Max-X:-140.000000 Max-Y:140.000000 Max-Z:140.000000 Steps/mm-X:644.000000 Steps/mm-Y:644.000000 Steps/mm-Z:644.000000 Steps--A: 40.000000 Print sets: 6
> U2:0.00 U3:0.00 U10:0.00 U11:0.00 U12:0.00 U13:1.00
> Set#0  Name:"Set 0"
>   ND:0.30 LT:0.15 SW:0.47 ST:1.00 HW:0.50 HS:4.00 HL:3.00 XW:0.55 XS:6.00 XL:3.00 SV:30.00 
>   HV:40.00 XV:40.00 JS:150.00 SZ:1.00 HZ:1.05 SZ:0.90 FZ:0.75 
>   O1:20.00 O2:6.00 O3:1.00 O4:3000.00 O5:3000.00 O6:3000.00 U1:0.00 U2:0.00 U3:0.00 U4:0.00 U5:0.00 U6:0.00 
> Set#1  Name:"Set 1"
>   ND:0.30 LT:0.20 SW:0.50 ST:1.00 HW:0.52 HS:4.00 HL:3.00 XW:0.55 XS:6.00 XL:3.00 SV:35.00 
>   HV:45.00 XV:50.00 JS:150.00 SZ:1.00 HZ:1.05 SZ:0.90 FZ:1.00 
>   O1:20.00 O2:6.00 O3:1.00 O4:3000.00 O5:3000.00 O6:3000.00 U1:0.00 U2:0.00 U3:0.00 U4:0.00 U5:0.00 U6:0.00 
> Set#2  Name:"Set 2"
>   ND:0.30 LT:0.25 SW:0.53 ST:1.00 HW:0.55 HS:6.00 HL:3.00 XW:0.57 XS:8.00 XL:3.00 SV:50.00 
>   HV:60.00 XV:70.00 JS:150.00 SZ:1.00 HZ:1.05 SZ:0.90 FZ:1.33 
>   O1:20.00 O2:6.00 O3:1.00 O4:3000.00 O5:6000.00 O6:6000.00 U1:0.00 U2:0.00 U3:0.00 U4:0.00 U5:0.00 U6:0.00 
> Set#3  Name:"Set 3"
>   ND:0.30 LT:0.30 SW:0.55 ST:1.00 HW:0.57 HS:6.00 HL:3.00 XW:0.60 XS:8.00 XL:3.00 SV:50.00 
>   HV:60.00 XV:70.00 JS:150.00 SZ:1.00 HZ:1.05 SZ:0.90 FZ:1.65 
>   O1:20.00 O2:6.00 O3:1.00 O4:3000.00 O5:6000.00 O6:6000.00 U1:0.00 U2:0.00 U3:0.00 U4:0.00 U5:0.00 U6:0.00 
> Set#4  Name:"Set 4"
>   ND:0.30 LT:0.35 SW:0.60 ST:1.00 HW:0.63 HS:6.00 HL:3.00 XW:0.66 XS:8.00 XL:3.00 SV:50.00 
>   HV:60.00 XV:70.00 JS:150.00 SZ:1.00 HZ:1.05 SZ:0.90 FZ:2.10 
>   O1:20.00 O2:6.00 O3:1.00 O4:3000.00 O5:6000.00 O6:6000.00 U1:0.00 U2:0.00 U3:0.00 U4:0.00 U5:0.00 U6:0.00 
> Set#5  Name:"Set 5"
>   ND:0.30 LT:0.40 SW:0.65 ST:1.00 HW:0.68 HS:6.00 HL:3.00 XW:0.72 XS:8.00 XL:3.00 SV:50.00 
>   HV:60.00 XV:60.00 JS:150.00 SZ:1.00 HZ:1.05 SZ:0.90 FZ:2.60 
>   O1:20.00 O2:6.00 O3:1.00 O4:3000.00 O5:6000.00 O6:6000.00 U1:0.00 U2:0.00 U3:0.00 U4:0.00 U5:0.00 U6:0.00 

this is what I get when UP! Software is running and I try to run the up3dinfo tool:
![up3dinfo error usb](https://cloud.githubusercontent.com/assets/6355171/18867969/14a99f72-84af-11e6-8665-15ab34828cd6.jpg)
so... this is the problem I think. just try to run up3dinfo when no other software connect to the printer...

**Comment by kscheff** [comment]
strange PID ... but it shows that your firmware is 3.07. This should report internally in https://github.com/UP3D-gcode/UP3D/blob/master/UP3DCOMMON/up3d.c 
line 124  
`if( _up3d_connected_fw_version<330 )`
as number 307. Could you verify that?

**Comment by yanivg101** [comment]
how can I verify what?
I can't compile any code on my PC (have no environment for that), I can only run the tools from the last compilation here on Github.
I will try to 3D print some cube and report.

**Comment by kscheff** [comment]
@yanivg101 it seems that the UP! software 2.18 reports a generic PID_0001. The real PID when in  printer mode should be seen in device manager like @arhi showed in https://github.com/UP3D-gcode/UP3D/issues/2#issue-179058496

As long as it works you don't need to compile it.

**Comment by yanivg101** [comment]
I can share my screen if it's help.
(yanivg101 at gmail dot com)
